### GET Server Time
### Response schema:
### Schema
###
###    result
###    object
###    unixtime
###    integer
###
###    Unix timestamp
###    rfc1123
###    string
###
###    RFC 1123 time format
###    error
###    string[]{
###
### Response example:
### {
###   "error": [],
###   "result": {
###     "unixtime": 1688669448,
###     "rfc1123": "Thu, 06 Jul 23 18:50:48 +0000"
###   }
### }
GET https://api.kraken.com/0/public/Time

### Get System Status
### Response schema:
### Schema
###
###    result
###    status
###    string
###
###    Possible values: [online, maintenance, cancel_only, post_only]
###
###    Current system status:
###        online Kraken is operating normally. All order types may be submitted and trades can occur.
###        maintenance The exchange is offline. No new orders or cancellations may be submitted.
###        cancel_only Resting (open) orders can be cancelled but no new orders may be submitted. No trades will occur.
###        post_only Only post-only limit orders can be submitted. Existing orders may still be cancelled. No trades will occur.
###    timestamp
###    string
###
###    Current timestamp (RFC3339)
###    error
###    string[]
###
### Response example:
### {
###   "error": [],
###   "result": {
###     "status": "online",
###     "timestamp": "2023-07-06T18:52:00Z"
###   }
### }
GET https://api.kraken.com/0/public/SystemStatus

### Get Asset Info
### Request schema:
### Query Parameters
###
###     asset
###     string
###
###     Comma delimited list of assets to get info on (optional, default all available assets)
###     Example: XBT,ETH
###     aclass
###     string
###
###     Asset class (optional, default: currency)
###     Example: currency
###
### Response schema:
### Schema
###
###     result
###     object
###     property name*
###     AssetInfo
###
###     Asset Info
###     aclass
###     string
###
###     Asset Class
###     altname
###     string
###
###     Alternate name
###     decimals
###     integer
###
###     Number of decimal places for record keeping amounts of this asset
###     display_decimals
###     integer
###
###     Number of decimal places shown for display purposes in frontends
###     collateral_value
###     number
###
###     Valuation as margin collateral (if applicable)
###     status
###     string
###
###     Status of asset. Possible values: enabled, deposit_only, withdrawal_only, funding_temporarily_disabled.
###     error
###     string[]
###
### Response example:
### {
###   "error": [],
###   "result": {
###     "XXBT": {
###       "aclass": "currency",
###       "altname": "XBT",
###       "decimals": 10,
###       "display_decimals": 5,
###       "collateral_value": 1,
###       "status": "enabled"
###     },
###     "ZEUR": {
###       "aclass": "currency",
###       "altname": "EUR",
###       "decimals": 4,
###       "display_decimals": 2,
###       "collateral_value": 1,
###       "status": "enabled"
###     },
###     "ZUSD": {
###       "aclass": "currency",
###       "altname": "USD",
###       "decimals": 4,
###       "display_decimals": 2,
###       "collateral_value": 1,
###       "status": "enabled"
###     }
###   }
### }
GET https://api.kraken.com/0/public/Assets

### Get Tradable Asset Pairs
### Request schema:
### Query Parameters
###
###     pair
###     string
###
###     Asset pairs to get data for
###     Example: BTC/USD,ETH/BTC
###     info
###     string
###
###     Possible values: [info, leverage, fees, margin]
###
###     Default value: info
###
###     Info to retrieve (optional)
###         info = all info
###         leverage = leverage info
###         fees = fees schedule
###         margin = margin info
###     country_code
###     string
###
###     Filter for response to only include pairs available in provided countries/regions
###     Example: US:TX,GB,CA
###
### Response schema:
### Schema
###
###     result
###     object
###
###     Pair names and their info
###     property name*
###     AssetPair
###
###     Trading Asset Pair
###     altname
###     string
###
###     Alternate pair name
###     wsname
###     string
###
###     WebSocket pair name (if available)
###     aclass_base
###     string
###
###     Asset class of base component
###     base
###     string
###
###     Asset ID of base component
###     aclass_quote
###     string
###
###     Asset class of quote component
###     quote
###     string
###
###     Asset ID of quote component
###     lot
###     stringdeprecated
###
###     Volume lot size
###     pair_decimals
###     integer
###
###     Number of decimal places for prices in this pair
###     cost_decimals
###     integer
###
###     Number of decimal places for cost of trades in pair (quote asset terms)
###     lot_decimals
###     integer
###
###     Number of decimal places for volume (base asset terms)
###     lot_multiplier
###     integer
###
###     Amount to multiply lot volume by to get currency volume
###     leverage_buy
###     integer[]
###
###     Array of leverage amounts available when buying
###     leverage_sell
###     integer[]
###
###     Array of leverage amounts available when selling
###     fees
###     array[]
###
###     Fee schedule array in [<volume>, <percent fee>] tuples
###     fees_maker
###     array[]
###
###     Maker fee schedule array in [<volume>, <percent fee>] tuples (if on maker/taker)
###     fee_volume_currency
###     string
###
###     Volume discount currency
###     margin_call
###     integer
###
###     Margin call level
###     margin_stop
###     integer
###
###     Stop-out/liquidation margin level
###     ordermin
###     string
###
###     Minimum order size (in terms of base currency)
###     costmin
###     string
###
###     Minimum order cost (in terms of quote currency)
###     tick_size
###     string
###
###     Minimum increment between valid price levels
###     status
###     string
###
###     Status of asset. Possible values: online, cancel_only, post_only, limit_only, reduce_only.
###     long_position_limit
###     integer
###
###     Maximum long margin position size (in terms of base currency)
###     short_position_limit
###     integer
###
###     Maximum short margin position size (in terms of base currency)
###     error
###     string[]
###
### Response example:
### {
###   "error": [],
###   "result": {
###     "XETHXXBT": {
###       "altname": "ETHXBT",
###       "wsname": "ETH/XBT",
###       "aclass_base": "currency",
###       "base": "XETH",
###       "aclass_quote": "currency",
###       "quote": "XXBT",
###       "lot": "unit",
###       "cost_decimals": 6,
###       "pair_decimals": 5,
###       "lot_decimals": 8,
###       "lot_multiplier": 1,
###       "leverage_buy": [
###         2,
###         3,
###         4,
###         5
###       ],
###       "leverage_sell": [
###         2,
###         3,
###         4,
###         5
###       ],
###       "fees": [
###         [
###           0,
###           0.26
###         ],
###         [
###           50000,
###           0.24
###         ],
###         [
###           100000,
###           0.22
###         ],
###         [
###           250000,
###           0.2
###         ],
###         [
###           500000,
###           0.18
###         ],
###         [
###           1000000,
###           0.16
###         ],
###         [
###           2500000,
###           0.14
###         ],
###         [
###           5000000,
###           0.12
###         ],
###         [
###           10000000,
###           0.1
###         ]
###       ],
###       "fees_maker": [
###         [
###           0,
###           0.16
###         ],
###         [
###           50000,
###           0.14
###         ],
###         [
###           100000,
###           0.12
###         ],
###         [
###           250000,
###           0.1
###         ],
###         [
###           500000,
###           0.08
###         ],
###         [
###           1000000,
###           0.06
###         ],
###         [
###           2500000,
###           0.04
###         ],
###         [
###           5000000,
###           0.02
###         ],
###         [
###           10000000,
###           0
###         ]
###       ],
###       "fee_volume_currency": "ZUSD",
###       "margin_call": 80,
###       "margin_stop": 40,
###       "ordermin": "0.01",
###       "costmin": "0.00002",
###       "tick_size": "0.00001",
###       "status": "online",
###       "long_position_limit": 1100,
###       "short_position_limit": 400
###     },
###     "XXBTZUSD": {
###       "altname": "XBTUSD",
###       "wsname": "XBT/USD",
###       "aclass_base": "currency",
###       "base": "XXBT",
###       "aclass_quote": "currency",
###       "quote": "ZUSD",
###       "lot": "unit",
###       "cost_decimals": 5,
###       "pair_decimals": 1,
###       "lot_decimals": 8,
###       "lot_multiplier": 1,
###       "leverage_buy": [
###         2,
###         3,
###         4,
###         5
###       ],
###       "leverage_sell": [
###         2,
###         3,
###         4,
###         5
###       ],
###       "fees": [
###         [
###           0,
###           0.26
###         ],
###         [
###           50000,
###           0.24
###         ],
###         [
###           100000,
###           0.22
###         ],
###         [
###           250000,
###           0.2
###         ],
###         [
###           500000,
###           0.18
###         ],
###         [
###           1000000,
###           0.16
###         ],
###         [
###           2500000,
###           0.14
###         ],
###         [
###           5000000,
###           0.12
###         ],
###         [
###           10000000,
###           0.1
###         ]
###       ],
###       "fees_maker": [
###         [
###           0,
###           0.16
###         ],
###         [
###           50000,
###           0.14
###         ],
###         [
###           100000,
###           0.12
###         ],
###         [
###           250000,
###           0.1
###         ],
###         [
###           500000,
###           0.08
###         ],
###         [
###           1000000,
###           0.06
###         ],
###         [
###           2500000,
###           0.04
###         ],
###         [
###           5000000,
###           0.02
###         ],
###         [
###           10000000,
###           0
###         ]
###       ],
###       "fee_volume_currency": "ZUSD",
###       "margin_call": 80,
###       "margin_stop": 40,
###       "ordermin": "0.0001",
###       "costmin": "0.5",
###       "tick_size": "0.1",
###       "status": "online",
###       "long_position_limit": 250,
###       "short_position_limit": 200
###     }
###   }
### }
GET https://api.kraken.com/0/public/AssetPairs

### Get Ticker Information
### Request schema:
### Query Parameters
###
###     pair
###     string
###
###     Asset pair to get data for (optional, default: all tradeable exchange pairs)
###     Example: XBTUSD
### Response schema:
### Schema
###
###     result
###     object
###     property name*
###     AssetTickerInfo
###
###     Asset Ticker Info
###     a
###     string[]
###
###     Ask [<price>, <whole lot volume>, <lot volume>]
###     b
###     string[]
###
###     Bid [<price>, <whole lot volume>, <lot volume>]
###     c
###     string[]
###
###     Last trade closed [<price>, <lot volume>]
###     v
###     string[]
###
###     Volume [<today>, <last 24 hours>]
###     p
###     string[]
###
###     Volume weighted average price [<today>, <last 24 hours>]
###     t
###     integer[]
###
###     Number of trades [<today>, <last 24 hours>]
###     l
###     string[]
###
###     Low [<today>, <last 24 hours>]
###     h
###     string[]
###
###     High [<today>, <last 24 hours>]
###     o
###     string
###
###     Today's opening price
###     error
###     string[]
###
### Response example:
### {
###   "error": [],
###   "result": {
###     "XXBTZUSD": {
###       "a": [
###         "30300.10000",
###         "1",
###         "1.000"
###       ],
###       "b": [
###         "30300.00000",
###         "1",
###         "1.000"
###       ],
###       "c": [
###         "30303.20000",
###         "0.00067643"
###       ],
###       "v": [
###         "4083.67001100",
###         "4412.73601799"
###       ],
###       "p": [
###         "30706.77771",
###         "30689.13205"
###       ],
###       "t": [
###         34619,
###         38907
###       ],
###       "l": [
###         "29868.30000",
###         "29868.30000"
###       ],
###       "h": [
###         "31631.00000",
###         "31631.00000"
###       ],
###       "o": "30502.80000"
###     }
###   }
### }
GET https://api.kraken.com/0/public/Time

### Get OHLC Data
### Request schema:
### Query Parameters
###
###     pair
###     stringrequired
###
###     Asset pair to get data for
###     Example: XBTUSD
###     interval
###     integer
###
###     Possible values: [1, 5, 15, 30, 60, 240, 1440, 10080, 21600]
###
###     Default value: 1
###
###     Time frame interval in minutes
###     Example: 60
###     since
###     integer
###
###     Return OHLC entries since the given timestamp (intended for incremental updates)
###     Example: 1688671200
###
### Response schema:
### Schema
###
###     result
###     object
###     last
###     integer
###
###     ID to be used as since when polling for new, committed OHLC data
###     property name*
###     TickData
###
###     Possible values: >= 8, <= 8
###
###     Array of tick data arrays [int <time>, string <open>, string <high>, string <low>, string <close>, string <vwap>, string <volume>, int <count>]
###     Array [
###     type
###     items object
###
###     Possible values: >= 8, <= 8
###     oneOf
###         string
###         integer
###
###     string
###     ]
###     error
###     string[]
###
### Response example:
### {
###   "error": [],
###   "result": {
###     "XXBTZUSD": [
###       [
###         1688671200,
###         "30306.1",
###         "30306.2",
###         "30305.7",
###         "30305.7",
###         "30306.1",
###         "3.39243896",
###         23
###       ],
###       [
###         1688671260,
###         "30304.5",
###         "30304.5",
###         "30300.0",
###         "30300.0",
###         "30300.0",
###         "4.42996871",
###         18
###       ],
###       [
###         1688671320,
###         "30300.3",
###         "30300.4",
###         "30291.4",
###         "30291.4",
###         "30294.7",
###         "2.13024789",
###         25
###       ],
###       [
###         1688671380,
###         "30291.8",
###         "30295.1",
###         "30291.8",
###         "30295.0",
###         "30293.8",
###         "1.01836275",
###         9
###       ]
###     ],
###     "last": 1688672160
###   }
### }
GET https://api.kraken.com/0/public/OHLC

### Get Order Book
### Request schema:
### Query Parameters
###
###     pair
###     stringrequired
###
###     Asset pair to get data for
###     Example: XBTUSD
###     count
###     integer
###
###     Possible values: >= 1 and <= 500
###
###     Default value: 100
###
###     Maximum number of asks/bids
###     Example: 2
###
### Response schema:
### Schema
###
###     result
###     object
###     property name*
###     OrderBook
###
###     Asset Pair Order Book Entries
###     asks
###     array[]
###
###     Possible values: >= 3, <= 3
###
###     Ask side array of entries [<price>, <volume>, <timestamp>]
###     bids
###     array[]
###
###     Possible values: >= 3, <= 3
###
###     Bid side array of entries [<price>, <volume>, <timestamp>]
###     error
###     string[]
###
### Response example:
### {
###   "error": [],
###   "result": {
###     "XXBTZUSD": {
###       "asks": [
###         [
###           "30384.10000",
###           "2.059",
###           1688671659
###         ],
###         [
###           "30387.90000",
###           "1.500",
###           1688671380
###         ],
###         [
###           "30393.70000",
###           "9.871",
###           1688671261
###         ]
###       ],
###       "bids": [
###         [
###           "30297.00000",
###           "1.115",
###           1688671636
###         ],
###         [
###           "30296.70000",
###           "2.002",
###           1688671674
###         ],
###         [
###           "30289.80000",
###           "5.001",
###           1688671673
###         ]
###       ]
###     }
###   }
### }
GET https://api.kraken.com/0/public/Depth

### Get Recent Trades
### Request schema:
### Query Parameters
###
###     pair
###     stringrequired
###
###     Asset pair to get data for
###     Example: XBTUSD
###     since
###     string
###
###     Return trade data since given timestamp
###     Example: 1616663618
###     count
###     integer
###
###     Possible values: >= 1 and <= 1000
###
###     Default value: 1000
###
###     Return specific number of trades, up to 1000
###     Example: 2
###
### Response schema:
### Schema
###
###     result
###     object
###     last
###     string
###
###     ID to be used as since when polling for new trade data
###     property name*
###     TickData
###
###     Array of trade entries [<price>, <volume>, <time>, <buy/sell>, <market/limit>, <miscellaneous>, <trade_id>]
###     Array [
###     type
###     items object
###     oneOf
###         string
###         number
###
###     string
###     ]
###     error
###     string[]
###
### Response example:
### {
###   "error": [],
###   "result": {
###     "XXBTZUSD": [
###       [
###         "30243.40000",
###         "0.34507674",
###         1688669597.8277369,
###         "b",
###         "m",
###         "",
###         61044952
###       ],
###       [
###         "30243.30000",
###         "0.00376960",
###         1688669598.2804112,
###         "s",
###         "l",
###         "",
###         61044953
###       ],
###       [
###         "30243.30000",
###         "0.01235716",
###         1688669602.698379,
###         "s",
###         "m",
###         "",
###         61044956
###       ]
###     ],
###     "last": "1688671969993150842"
###   }
### }
GET https://api.kraken.com/0/public/Trades

### Get Recent Trades
### Request schema:
### Query Parameters
###
###     pair
###     stringrequired
###
###     Asset pair to get data for
###     Example: XBTUSD
###     since
###     integer
###
###     Returns spread data since given timestamp. Optional, intended for incremental updates within available dataset (does not contain all historical spreads).
###     Example: 1678219570
###
### Response schema:
### Schema
###
###     result
###     object
###     last
###     integer
###
###     ID to be used as since when polling for new spread data
###     property name*
###     SpreadData
###
###     Array of spread entries [int <time>, string <bid>, string <ask>]
###     Array [
###     type
###     items object
###     oneOf
###         string
###         integer
###
###     string
###     ]
###     error
###     string[]
###
### Response example:
### {
###   "error": [],
###   "result": {
###     "XXBTZUSD": [
###       [
###         1688671834,
###         "30292.10000",
###         "30297.50000"
###       ],
###       [
###         1688671834,
###         "30292.10000",
###         "30296.70000"
###       ],
###       [
###         1688671834,
###         "30292.70000",
###         "30296.70000"
###       ]
###     ],
###     "last": 1688672106
###   }
### }
GET https://api.kraken.com/0/public/Spread