//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsonConverterTests {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RestResponses {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RestResponses() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("JsonConverterTests.RestResponses", typeof(RestResponses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ValidOrderBookResponse {
            get {
                return ResourceManager.GetString("ValidAssetPairResponse", resourceCulture);
            }
        }
        
        internal static string OrderBookExample {
            get {
                return ResourceManager.GetString("OrderBookExample", resourceCulture);
            }
        }
        
        internal static string ServerTimeExample {
            get {
                return ResourceManager.GetString("ServerTimeExample", resourceCulture);
            }
        }
        
        internal static string SystemStatusExample {
            get {
                return ResourceManager.GetString("SystemStatusExample", resourceCulture);
            }
        }
        
        internal static string AssetInfoExample {
            get {
                return ResourceManager.GetString("AssetInfoExample", resourceCulture);
            }
        }
        
        internal static string TradableAssetPairExample {
            get {
                return ResourceManager.GetString("TradableAssetPairExample", resourceCulture);
            }
        }
        
        internal static string TickerInformationExample {
            get {
                return ResourceManager.GetString("TickerInformationExample", resourceCulture);
            }
        }
        
        internal static string OhlcDataExample {
            get {
                return ResourceManager.GetString("OhlcDataExample", resourceCulture);
            }
        }
        
        internal static string RecentTradesExample {
            get {
                return ResourceManager.GetString("RecentTradesExample", resourceCulture);
            }
        }
        
        internal static string RecentSpreadsExample {
            get {
                return ResourceManager.GetString("RecentSpreadsExample", resourceCulture);
            }
        }
    }
}
